services:
  mongodb:
    image: mongo
    container_name: bt-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      mynet:
        ipv4_address: 172.28.1.4

  backend-asr:
    build: ./backend-asr
    container_name: speech-to-text-server
    ports: 
      - "5001:5001"
    depends_on:
      - mongodb
    working_dir: /app/src
    command: ["python", "app.py"]
    networks:
      mynet:
        ipv4_address: 172.28.1.5

volumes:
  mongodb_data:

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
